options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Deploy the workflow
# - id: 'deploy-workflow'
#   name: 'gcr.io/cloud-builders/gcloud'
#   args: ['workflows', 'deploy', '$BRANCH_NAME', '--source', 'workflow.yaml']

# steps:
# - name: 'ubuntu'
#   entrypoint: '/bin/bash'
#   args: ['-c', 'echo Workflow Name: $_WORKFLOW_NAME-$BRANCH_NAME']

  # Make sure the deploy-workflow.sh script is executable
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'chmod'
    args: ['+x', './deploy-workflow.sh']

  # Execute the deploy-workflow.sh script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash'
    args: ['./deploy-workflow.sh']