steps:
# Deploy the workflow
- id: 'deploy-workflow'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['workflows', 'deploy', '$BRANCH_NAME', '--source', 'workflow.yaml']

# steps:
# - name: 'ubuntu'
#   entrypoint: '/bin/bash'
#   args: ['-c', 'echo Workflow Name: $_WORKFLOW_NAME-$BRANCH_NAME']