options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Make sure the deploy-workflow.sh script is executable
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'chmod'
    args: ['+x', './deploy-sample-workflow.sh']

  # Execute the deploy-workflow.sh script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash'
    args: ['./deploy-sample-workflow.sh']
  
  # Make sure the deploy-workflow.sh script is executable
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'chmod'
    args: ['+x', './deploy-bq-workflow.sh']

  # Execute the deploy-workflow.sh script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: '/bin/bash'
    args: ['./deploy-bq-workflow.sh']